### ISSUE TITLE
Line continuation in not supported

### ISSUE THREAD

**Issue by mboughaba** [mboughaba/i3config.vim#1]
i3 config line continuation is not supported, i3config.vim will highlight split line using Error group.

``` vim
#27) Line continuation
bindsym Mod1+f \
fullscreen toggle

font \
xft:System San Francisco Display, \
FontAwesome 10
```

**Comment by xPMo** [comment]
Hey, if you're still maintaining this (I just found this after considering writing something like this myself) I suggest looking at the `sh` syntax file for a guide. Unfortunately, this requires a rewrite converting a lot of your `match` statements into `regions`.  Thankfully once you've done one you've done them all.
