### ISSUE TITLE
filetype

### ISSUE THREAD

**Issue by tofulm** [mboughaba/i3config.vim#10]
hi,
You can add in readme.me :
``
I recommend you to add # vim:filetype=i3config at the end of your i3 config file.
``
cf : https://github.com/PotatoesMaster/i3-vim-syntax

thanks

**Comment by mboughaba** [comment]
Hi @tofulm 

I have a section for File type detection, please check it.
https://github.com/mboughaba/i3config.vim#file-type-detection
