### ISSUE TITLE
Dark font color on dark theme

### ISSUE THREAD

**Issue by wdlaszlo** [mboughaba/i3config.vim#11]
I took your plugin to view my i3 config nice, but there is a problem on dark themes because of dark fonts. Take a look at photo.

Could be fixed? :+1: 

https://i.imgur.com/NTgyRL2.png

**Comment by mboughaba** [comment]
Sure we can fix this, I had the same issue with a similar theme 🙄 
I'll see if I can do something for that

**Comment by mboughaba** [comment]
Hi @wdlaszlo 
This is indeed a bug, but might take sometime to fix.
I personally use [Solarized](https://github.com/altercation/vim-colors-solarized) which seems to work properly for me.

Is your case specific to a certain theme ? if so can you let me know which theme are you using?

Cheers

**Comment by wdlaszlo** [comment]
I'm using Ambiance theme. 
With Solarized looks ok, but I'm not a big fan of Solarized.

**Comment by mboughaba** [comment]
`i3config.vim` uses standard predefined vim syntax groups https://github.com/mboughaba/i3config.vim/blob/c68f86f38612f6df6704a61adf26ae8cbe0056dc/syntax/i3config.vim#L172

`Ambiance` is choosing to use a minimal set of highlight groups as shown in their README file. So not much I can do here :smile:
