### ISSUE TITLE
Filetype detection quick fix

### ISSUE THREAD

**Issue by ghost** [mboughaba/i3config.vim#15]
Automatic filetype detection can be fixed by adding `# vim:filetype=i3config` at the end of your config

**Comment by mboughaba** [comment]
yes that's right. I didn't put that in the `README`. I would highly appreciate if you can make a small PR to clarify that in the README file section: `File type detection` 

### File type detection

There is no specific extension for i3 config file.
For auto detection, the recommended method is to rename your file to something like:

+ .i3.config
+ i3.config
+ something.i3config
+ something.i3.config

> This way you can keep your file clean somewhere in a
dotfile repository and have it symlinked to ~/.i3/config

If you don't want to, then you can always do:

```vim
:set ft=i3config
```

or

```vim
:set filetype=i3config
```

**Comment by mboughaba** [comment]
No need to keep it open as no action required.
