### ISSUE TITLE
ArbitraryCommand syntax group is invisible

### ISSUE THREAD

**Issue by keysmashes** [mboughaba/i3config.vim#16]
In situations like `for_window` rules, the command that will be executed is invisible:

![image](https://user-images.githubusercontent.com/9433472/50614266-218b1a80-0ed8-11e9-829c-ce9fe17b0be0.png)

This is because the command is matched by i3config.vim's `ArbitraryCommand` syntax group, which is linked to Vim's `Ignore` group:

https://github.com/mboughaba/i3config.vim/blob/c68f86f38612f6df6704a61adf26ae8cbe0056dc/syntax/i3config.vim#L233

Per the Vim documentation (`:h group-name`), `Ignore` is "left blank, hidden" – it seems strange that you would want to hide the command for a `for_window` rule, especially given that the commands in `exec` statements aren't hidden.

Please can `ArbitraryCommand` be linked to something more reasonable, or even nothing at all (like `Exec`)?

**Comment by mboughaba** [comment]
Hi @anowlcalledjosh,

Thanks for the issue report. It is indeed a bug. I will make a quick PR to solve it.
Let me know if it is what you had in mind.

![for_window_cmd](https://user-images.githubusercontent.com/3800584/50736779-dcaa0100-11c1-11e9-90f5-ed8b6790ddc1.png)

Cheers,
Mo
