### ISSUE TITLE
Add syntax support for gaps

### ISSUE THREAD

**Issue by Jab2870** [mboughaba/i3config.vim#17]
Hi,

Thanks for making this. Would you consider adding syntax support for i3-gaps specific properties such as `gaps_outer`, `gaps_inner` & `smart_gaps`?

<https://github.com/Airblader/i3>

**Comment by mboughaba** [comment]
Hi,

Sure. Initial Gaps support has been added thanks to @jihbuomj in https://github.com/mboughaba/i3config.vim/commit/085410a99032c5cce94911de3093f21d31ab5883

I guess now we need to add support for the mentioned keyword `gaps_outer, gaps_inner & smart_gaps`

Unless someone wants to pick this up, I will check it in the coming days...

Mo

**Comment by codebork** [comment]
@Jab2870 I believe smart_gaps should be covered now by https://github.com/mboughaba/i3config.vim/commit/33c374e8e87daedd71daa03ba5e23cc1a84cb607, but I'm unsure what you mean by gaps_outer and gaps_inner. Are those not already covered by https://github.com/mboughaba/i3config.vim/commit/085410a99032c5cce94911de3093f21d31ab5883?

**Comment by mboughaba** [comment]
The gaps commands are part of the i3 New features.
As shown below, some of the examples from the above mentioned repo are not accepted by this plugin.

![image](https://user-images.githubusercontent.com/3800584/52435897-39773f00-2b13-11e9-9907-47be44c72914.png)

**Comment by mboughaba** [comment]
![image](https://user-images.githubusercontent.com/3800584/52437653-b60c1c80-2b17-11e9-8fb0-3ce71f41a7b6.png)
