### ISSUE TITLE
Add highlighting for `set_from_resource`

### ISSUE THREAD

**Issue by mattmahn** [mboughaba/i3config.vim#2]
In the [release][release-notes] of i3 v4.13, a new command [`set_from_resource`][xresources] was added that allows i3 variables to be set from values in the X resource database.

[release-notes]: http://i3wm.org/downloads/RELEASE-NOTES-4.13.txt
[xresources]: http://i3wm.org/docs/userguide.html#xresources

**Comment by mboughaba** [comment]
Hello Mattmahn,
I won't be able to add this feature in the coming months. In the meantime, you can always make a PR.
Cheers
