### ISSUE TITLE
Do not overwrite built in highlights + you should namespace your own highlight groups

### ISSUE THREAD

**Issue by dsifford** [mboughaba/i3config.vim#22]
Hi there,

I maintain the [Dracula](https://github.com/dracula/vim) color scheme and I noticed that this syntax does some things that, IMHO, are not ideal.

The first being that the plugin redefines highlights for _known_ highlight groups. This breaks Dracula's highlights and almost certainly the highlights of other color schemes.

https://github.com/mboughaba/i3config.vim/blob/9f5c292ca528e97a7e44f755a71b1efa7bfd23f7/syntax/i3config.vim#L182-L184

The second thing is that the custom syntax groups are not namespaced.

https://github.com/mboughaba/i3config.vim/blob/9f5c292ca528e97a7e44f755a71b1efa7bfd23f7/syntax/i3config.vim#L185-L188

You should append `i3_` (or something) to those groups to ensure you're not stomping on other syntax groups.

So, something like this...

```vim
 hi! def link i3_FontContent Type 
 hi! def link i3_FocusOnActivationType Type 
 hi! def link i3_PopupOnFullscreenType Type 
 hi! def link i3_OrientationKeyword Type 
```
(and obviously also adjust them up in the main definitions as well).

Thanks for considering.

**Comment by mboughaba** [comment]
Hey @dsifford 

Sure thing, I will take a look at that. I use Darcula too (best color scheme ever IMO) and I didn't notice any issues but maybe that's just my taste 😀 

Cheers,
Mo
