### ISSUE TITLE
focus_follows_mouse

### ISSUE THREAD

**Issue by nogerine** [mboughaba/i3config.vim#25]
The following config line is highlighted in red:

`focus_follows_mouse false`

**Comment by nogerine** [comment]
Hmm... Seems like i3 is recognizing true/false in focus_follows_mouse, which is undocumented behaviour

**Comment by mboughaba** [comment]
according to the docs <https://i3wm.org/docs/userguide.html>

## 4.22. Focus follows mouse
By default, window focus follows your mouse movements as the mouse crosses window borders. However, if you have a setup where your mouse usually is in your way (like a touchpad on your laptop which you do not want to disable completely), you might want to disable focus follows mouse and control focus only by using your keyboard. The mouse will still be useful inside the currently active window (for example to click on links in your browser window).

### Syntax:

`focus_follows_mouse yes|no`

### Example:

`focus_follows_mouse no`

https://github.com/mboughaba/i3config.vim/blob/da2aeaa81a19af58fba5ce555519f6ca49108241/syntax/i3config.vim#L138

Looks like the syntax highlighting was able to spot an issue in the config 🤣 

Or we could log a bug report for i3 to clarify.. (maybe)
