### ISSUE TITLE
Almost no highlight in modes

### ISSUE THREAD

**Issue by vahnrr** [mboughaba/i3config.vim#26]
As you can see on the screenshot bellow there's next to no highlight on lines within a mode.

![mode_highlight](https://user-images.githubusercontent.com/46555942/58994747-dd3ad800-87f1-11e9-87db-22282a5c59c2.png)

**Comment by mboughaba** [comment]
Thanks for the report. 
I think it is an issue: https://i3wm.org/docs/userguide.html#binding_modes
Will look into it
