### ISSUE TITLE
'down' and 'up' arguments to the focus command are not highlighted

### ISSUE THREAD

**Issue by slavistan** [mboughaba/i3config.vim#27]
The `focus` and `move` commands take an argument specifying a direction: left, right, top, bottom. The `down` and `up` choices are not highlighted.

![image](https://user-images.githubusercontent.com/35600954/59551054-17377700-8f74-11e9-901d-8bcde12dc241.png)

**Comment by mboughaba** [comment]
thanks for the report, I will have a look soon.

**Comment by slavistan** [comment]
In fact, there are a few other keywords that lack highlighting.

![image](https://user-images.githubusercontent.com/35600954/59563851-6a2a3080-903f-11e9-8a07-7b1fb8a8b5ee.png)
I believe all of the white words are keywords although I'm not sure whether their color is just set to white in the colorscheme.

Kind regards and thanks a lot for your efforts!
