### ISSUE TITLE
title_align

### ISSUE THREAD

**Issue by keysmashes** [mboughaba/i3config.vim#28]
The [title_align](https://i3wm.org/docs/userguide.html#_window_title_alignment) option is highlighted in red:

![image](https://user-images.githubusercontent.com/9433472/61239684-66212980-a737-11e9-88b1-8f566a1abe20.png)

I guess it is not in the syntax highlighting files; it can take a value `left`, `center` or `right`.

**Comment by mboughaba** [comment]
Thanks for the report,
I will make a release soon, I could include a fix for this as well.
