### ISSUE TITLE
Problem with EasyMotion Plugin

### ISSUE THREAD

**Issue by sven1** [mboughaba/i3config.vim#3]
there are some problems with your i3config. If i rename my config in .i3.config for instance then your syntax highlighting works fine but the easymotion plugin dont work anymore. :(
if i dont use your syntax highlighting, so for example i dont change the name, then the easymotion plugin still works fine. I dont have a clue whats the problem. can't be the double <Leader>!?

**Comment by mboughaba** [comment]
Hi Sven1,

Oh sorry for the late reply I need to catch still.
I don't use easymotion so I can't check it.
Just for testing purposes... how about keeping the file name as is and creating a symlink to it with target .i3.config?

Would that make both easymotion and i3config happy?

**Comment by BerkeleyTrue** [comment]
I was also running into this issue. Not sure the exact cause is, but removing the filetype (i.e. `set ft=conf`) easymotion would work again. 

I've switched over to https://github.com/PotatoesMaster/i3-vim-syntax which works fine with easymotion. Really strange bug.

**Comment by mboughaba** [comment]
Hi @BerkeleyTrue,
not sure why you needed `set ft=conf`.
`i3config`doesn't require setting a filetype, you can achieve the same results by changing the file name as one of `.i3.config`, `i3.config`, `something.i3config`, `something.i3.config` or setting `set ft=i3config`

**Comment by BerkeleyTrue** [comment]
@mboughaba my comment was to demonstrate removing the i3config settings by setting filetype to conf(i.e. not i3config), not the otherway around.
