### ISSUE TITLE
Variables not always highlighted correctly

### ISSUE THREAD

**Issue by jrwrigh** [mboughaba/i3config.vim#31]
Below I have three different uses of variables that are all not working correctly in different ways.

![image](https://user-images.githubusercontent.com/20801821/77358132-e8261100-6d0e-11ea-9e56-5fc4ca3e278f.png)

```i3
set $def_border_pix 2
floating_modifier $mod
for_window [class="^.*"] border pixel $def_border_pix
default_border pixel $def_border_pix
default_floating_border normal
hide_edge_borders none
font pango:ShureTechMono Nerd Font Mono NoLiga 11

# change borders
bindsym $mod+u border none
bindsym $mod+y border pixel $def_border_pix
```

**Comment by mboughaba** [comment]
Thanks for the report @jrwrigh 
We should review the border style matching to make accept variable as well: https://github.com/mboughaba/i3config.vim/blob/24a7f69c0426d7f201085bfbbde857e82dbb8e25/syntax/i3config.vim#L91

I can take a look in couple of days if it is not picked by then
