### ISSUE TITLE
Consider merging i3config.vim into vim

### ISSUE THREAD

**Issue by hiqua** [mboughaba/i3config.vim#34]
Hi,

have you considered creating a pull request to merge your plugin into https://github.com/vim/vim/ ? Your plugin seems like a good candidate, and would make it more widespread.

**Comment by mboughaba** [comment]
I never thought about this. I will check what's needed and give it a try
Thanks Hiqua!

**Comment by hiqua** [comment]
Shall I look into it?

**Comment by hiqua** [comment]
@mboughaba I've created a PR and I'll try to have it merged if the changes requested are not too big. The PR is there: https://github.com/vim/vim/pull/7969

Any feedback welcome. I've just taken your last version from master.

Your email address was in the files, so I left it as-is. Should I remove it instead?

**Comment by hiqua** [comment]
Merged, I'll do the maintenance in the upstream repo by default. Thanks!
